name: ordrestyring_common
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0


  intl: ^0.20.2
  timezone: ^0.10.0
  week_of_year: ^2.2.0
  graphql_flutter: ^5.1.2

  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1

  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/
    - assets/images/
